// 单词搭配数据：为 words_bank.js 中每个单词提供 2~3 条常见组合搭配 / 例句短语（英文搭配 + 中文意思），供单词卡片背面展示。
window.WORD_COLLOC = {
  "able": ["be able to do sth 能够做某事", "be able to help 能帮上忙"],
  "about": ["talk about 谈论", "think about 考虑", "about to do 即将做"],
  "above": ["above all 最重要的是", "the sky above 头顶的天空"],
  "actor": ["a famous actor 著名演员", "a movie actor 电影演员"],
  "add": ["add to 增添", "add up 加起来", "add...to 把…加到"],
  "afraid": ["be afraid of 害怕", "be afraid to do 不敢做"],
  "after": ["after school 放学后", "the day after 第二天", "look after 照顾"],
  "again": ["again and again 一次又一次", "see you again 再见"],
  "age": ["at the age of 在…岁时", "a boy of my age 同龄男孩"],
  "air": ["by air 乘飞机", "fresh air 新鲜空气", "in the air 在空中"],
  "airport": ["at the airport 在机场", "go to the airport 去机场"],
  "all": ["all day 一整天", "all over 到处", "not at all 一点也不"],
  "alone": ["live alone 独自生活", "leave me alone 别管我"],
  "also": ["and also 而且", "I also like 我也喜欢"],
  "always": ["always late 总是迟到", "always happy 总是开心"],
  "angry": ["be angry with 生…的气", "be angry at 对…生气"],
  "animal": ["a wild animal 野生动物", "keep an animal 养动物"],
  "answer": ["answer the phone 接电话", "the answer to 对…的答案"],
  "apple": ["an apple a day 一天一苹果", "red apple 红苹果"],
  "april": ["in April 在四月", "April Fool's Day 愚人节"],
  "arm": ["arm in arm 臂挽臂", "right arm 右臂"],
  "art": ["work of art 艺术品", "art class 美术课"],
  "aunt": ["my aunt 我的阿姨", "visit my aunt 看望阿姨"],
  "autumn": ["in autumn 在秋天", "autumn leaves 秋叶"],
  "baby": ["a baby boy 男婴", "baby food 婴儿食品"],
  "back": ["come back 回来", "at the back of 在…后面", "back home 回家"],
  "bad": ["be bad for 对…有害", "too bad 太糟了", "go bad 变质"],
  "bag": ["a school bag 书包", "a bag of 一袋"],
  "ball": ["play ball 打球", "a ball game 球类运动"],
  "banana": ["a banana 一根香蕉", "banana tree 香蕉树"],
  "bank": ["by the bank 在河岸旁", "go to the bank 去银行"],
  "bath": ["take a bath 洗澡", "bath water 洗澡水"],
  "beach": ["on the beach 在海滩", "go to the beach 去海滩"],
  "bean": ["green beans 青豆", "a bag of beans 一袋豆"],
  "bear": ["a black bear 黑熊", "bear pain 忍受疼痛"],
  "beautiful": ["a beautiful girl 漂亮女孩", "beautiful music 美妙音乐"],
  "bed": ["go to bed 去睡觉", "make the bed 铺床"],
  "beef": ["beef noodles 牛肉面", "roast beef 烤牛肉"],
  "before": ["before long 不久以后", "the day before 前一天"],
  "begin": ["begin with 以…开始", "begin to do 开始做"],
  "behind": ["fall behind 落后", "behind the door 门后"],
  "bell": ["ring the bell 按铃", "school bell 上课铃"],
  "best": ["best friend 最好的朋友", "do one's best 尽力", "the best 最好的"],
  "better": ["had better 最好", "better than 比…好", "get better 好转"],
  "big": ["a big city 大城市", "big news 大新闻"],
  "bird": ["a little bird 小鸟", "birds singing 鸟儿歌唱"],
  "birthday": ["happy birthday 生日快乐", "birthday party 生日聚会"],
  "black": ["black tea 红茶", "black and white 黑白"],
  "blue": ["blue sky 蓝天", "feel blue 感到忧伤"],
  "boat": ["by boat 乘船", "a small boat 小船"],
  "body": ["body language 肢体语言", "keep body 保持健康"],
  "book": ["a story book 故事书", "book a room 预订房间"],
  "boot": ["a pair of boots 一双靴子", "rubber boot 雨靴"],
  "born": ["be born 出生", "born in 出生于"],
  "borrow": ["borrow from 向…借", "borrow money 借钱"],
  "boss": ["my boss 我的老板", "boss of the company 公司老板"],
  "both": ["both of 两者都", "both...and 既…又"],
  "bottle": ["a bottle of 一瓶", "water bottle 水瓶"],
  "bottom": ["at the bottom 在底部", "bottom line 底线"],
  "box": ["a box of 一盒", "box office 售票处"],
  "boy": ["a good boy 好男孩", "boys and girls 孩子们"],
  "bread": ["a piece of bread 一片面包", "bread and butter 黄油面包"],
  "break": ["break down 出故障", "break the rule 违规", "have a break 休息"],
  "breakfast": ["have breakfast 吃早餐", "breakfast time 早餐时间"],
  "bridge": ["cross the bridge 过桥", "a bridge over 跨…的桥"],
  "brother": ["elder brother 哥哥", "little brother 弟弟"],
  "brown": ["brown hair 棕色头发", "brown sugar 红糖"],
  "brush": ["brush teeth 刷牙", "a paint brush 画笔"],
  "build": ["build up 建立", "build a house 盖房子"],
  "bus": ["by bus 乘公交", "miss the bus 错过公交"],
  "busy": ["be busy with 忙于", "busy day 忙碌的一天"],
  "buy": ["buy for 为…买", "buy a ticket 买票"],
  "bye": ["say bye 说再见", "bye bye 拜拜"],
  "cake": ["a piece of cake 一块蛋糕", "birthday cake 生日蛋糕"],
  "call": ["call up 打电话", "give a call 打个电话", "call for 要求"],
  "camera": ["a digital camera 数码相机", "take a camera 带相机"],
  "camp": ["summer camp 夏令营", "go camping 去露营"],
  "can": ["can do 能做", "as...as one can 尽可能", "can't help 忍不住"],
  "candy": ["a piece of candy 一颗糖", "candy store 糖果店"],
  "car": ["by car 乘汽车", "drive a car 开车"],
  "card": ["a birthday card 生日贺卡", "credit card 信用卡"],
  "care": ["take care of 照顾", "care about 在乎", "with care 小心地"],
  "careful": ["be careful with 小心", "careful driver 谨慎的司机"],
  "carry": ["carry on 继续", "carry out 执行"],
  "cat": ["a lazy cat 懒猫", "cat food 猫粮"],
  "catch": ["catch up 赶上", "catch a cold 感冒", "catch the bus 赶公交"],
  "center": ["in the center 在中心", "shopping center 购物中心"],
  "chair": ["sit on a chair 坐在椅子上", "a chair of 一把…椅子"],
  "cheese": ["a piece of cheese 一块奶酪", "cheese cake 芝士蛋糕"],
  "chicken": ["fried chicken 炸鸡", "chicken soup 鸡汤"],
  "child": ["a young child 小孩", "children's book 童书"],
  "chin": ["double chin 双下巴", "touch one's chin 摸下巴"],
  "city": ["a big city 大城市", "city life 城市生活"],
  "class": ["in class 在课堂上", "after class 课后", "classmate 同学"],
  "clean": ["clean up 打扫干净", "keep clean 保持清洁"],
  "clear": ["clear up 放晴", "make it clear 说清楚"],
  "clever": ["a clever boy 聪明的男孩", "clever idea 妙主意"],
  "clock": ["watch the clock 看时间", "alarm clock 闹钟"],
  "close": ["close to 靠近", "close the door 关门"],
  "clothes": ["a set of clothes 一套衣服", "wash clothes 洗衣服"],
  "cloud": ["a piece of cloud 一片云", "white clouds 白云"],
  "cloudy": ["a cloudy day 阴天", "It is cloudy today 今天多云"],
  "coat": ["a warm coat 暖和的外套", "put on a coat 穿上外套"],
  "coffee": ["a cup of coffee 一杯咖啡", "coffee shop 咖啡店"],
  "cold": ["catch a cold 感冒", "cold weather 寒冷天气", "feel cold 觉得冷"],
  "collect": ["collect stamps 集邮", "collect money 筹款"],
  "color": ["color blind 色盲", "bright color 鲜艳的颜色"],
  "come": ["come from 来自", "come back 回来", "come true 实现"],
  "computer": ["on the computer 在电脑上", "computer game 电脑游戏"],
  "cook": ["cook dinner 做晚饭", "a good cook 好厨师"],
  "cool": ["keep cool 保持凉爽", "cool down 冷静下来"],
  "copy": ["make a copy 复印一份", "copy the text 抄写课文"],
  "corner": ["in the corner 在角落", "around the corner 即将来临"],
  "cost": ["cost of living 生活成本", "at all costs 不惜一切"],
  "count": ["count on 依靠", "count from 从…数起"],
  "country": ["in the country 在乡村", "developing country 发展中国家"],
  "cousin": ["my cousin 我的表兄", "visit cousin 看望表亲"],
  "cover": ["cover up 掩盖", "cover with 用…覆盖"],
  "cow": ["milk a cow 挤牛奶", "a cow 一头牛"],
  "cross": ["cross the road 过马路", "cross out 划掉"],
  "cry": ["cry out 大声喊", "cry for 因…而哭"],
  "cup": ["a cup of 一杯", "tea cup 茶杯"],
  "cut": ["cut down 砍倒", "cut up 切碎", "cut the paper 剪纸"],
  "dad": ["my dad 我爸爸", "dad and mom 爸妈"],
  "daily": ["daily life 日常生活", "daily newspaper 日报"],
  "dance": ["dance to 随…跳舞", "a dance party 舞会"],
  "danger": ["in danger 处于危险", "out of danger 脱离危险"],
  "dark": ["after dark 天黑后", "dark room 暗室"],
  "date": ["date back 追溯到", "go on a date 约会"],
  "daughter": ["my daughter 我女儿", "daughter of 的女儿"],
  "day": ["day by day 一天天", "all day 一整天", "the other day 前几天"],
  "dead": ["dead end 死胡同", "drop dead 倒毙"],
  "dear": ["dear friend 亲爱的朋友", "Oh dear 哎呀"],
  "december": ["in December 在十二月", "December holiday 十二月假期"],
  "decide": ["decide on 决定", "decide to do 决定做"],
  "deep": ["deep sleep 熟睡", "deep water 深水"],
  "desk": ["at the desk 在书桌旁", "a desk lamp 台灯"],
  "dictionary": ["look up in a dictionary 查字典", "an English dictionary 英语词典"],
  "die": ["die of 死于", "die out 灭绝"],
  "dinner": ["have dinner 吃晚饭", "dinner time 晚餐时间"],
  "dirty": ["dirty clothes 脏衣服", "get dirty 弄脏"],
  "dish": ["do the dishes 洗碗", "a dish of 一盘"],
  "do": ["do well 做得好", "do one's best 尽力", "do homework 做作业"],
  "doctor": ["see a doctor 看医生", "a doctor 一名医生"],
  "dog": ["a pet dog 宠物狗", "dog food 狗粮"],
  "dollar": ["a dollar 一美元", "make a dollar 赚一美元"],
  "door": ["answer the door 应门", "open the door 开门"],
  "double": ["double room 双人间", "double click 双击"],
  "down": ["sit down 坐下", "down the street 沿街而下", "calm down 冷静"],
  "draw": ["draw a picture 画画", "draw near 临近"],
  "dream": ["dream of 梦想", "have a dream 有个梦想"],
  "dress": ["dress up 打扮", "get dressed 穿好衣服"],
  "drink": ["have a drink 喝一杯", "soft drink 软饮"],
  "drive": ["drive a car 开车", "drive sb mad 使…发疯"],
  "drop": ["drop by 顺道拜访", "drop out 退学"],
  "dry": ["dry up 干涸", "keep dry 保持干燥"],
  "duck": ["a duck 一只鸭", "duck soup 易事"],
  "each": ["each other 互相", "each day 每天"],
  "ear": ["ear to ear 咧嘴笑", "by ear 凭听觉"],
  "early": ["early morning 清晨", "as early as 早在"],
  "earth": ["on earth 究竟", "the earth 地球"],
  "east": ["in the east 在东方", "East Asia 东亚"],
  "easy": ["take it easy 放轻松", "easy to do 容易做"],
  "eat": ["eat out 外出就餐", "eat up 吃光"],
  "egg": ["a boiled egg 煮鸡蛋", "egg yolk 蛋黄"],
  "eight": ["eight o'clock 八点钟", "eight years old 八岁"],
  "eighteen": ["eighteen years 十八年", "age eighteen 十八岁"],
  "eighty": ["eighty percent 百分之八十", "eighty years 八十年"],
  "elder": ["elder sister 姐姐", "elder brother 哥哥"],
  "elephant": ["a big elephant 大象", "elephant trunk 象鼻"],
  "eleven": ["eleven e'clock 十一点", "eleven years 十一年"],
  "end": ["in the end 最后", "end up 最终", "at the end of 在…末尾"],
  "energy": ["full of energy 精力充沛", "save energy 节约能源"],
  "enjoy": ["enjoy doing 喜欢做", "enjoy oneself 玩得开心"],
  "enough": ["enough to 足够…", "good enough 够好", "more than enough 绰绰有余"],
  "enter": ["enter for 报名参加", "enter the room 进入房间"],
  "evening": ["in the evening 在晚上", "evening party 晚会"],
  "every": ["every day 每天", "every week 每周"],
  "everyone": ["everyone else 其他每个人", "Hello everyone 大家好"],
  "exact": ["exact same 完全一样", "to be exact 确切地说"],
  "example": ["for example 例如", "set an example 树立榜样"],
  "except": ["except for 除了", "nobody except 除…外没人"],
  "exercise": ["do exercise 做运动", "physical exercise 体育锻炼"],
  "expensive": ["too expensive 太贵", "expensive car 昂贵的车"],
  "eye": ["keep an eye on 留意", "in one's eyes 在…眼中"],
  "face": ["face to face 面对面", "face the music 承担后果"],
  "fall": ["fall down 跌倒", "fall asleep 入睡", "fall in love 坠入爱河"],
  "family": ["family member 家庭成员", "family name 姓氏"],
  "far": ["far away 遥远的", "so far 到目前为止", "far from 离…远"],
  "farm": ["on the farm 在农场", "farm house 农舍"],
  "fast": ["fast food 快餐", "run fast 跑得快"],
  "father": ["father and son 父子", "like a father 像父亲一样"],
  "fear": ["for fear of 生怕", "in fear 恐惧地"],
  "february": ["in February 在二月", "February holiday 二月假期"],
  "feed": ["feed on 以…为食", "feed the cat 喂猫"],
  "feel": ["feel like 想要", "feel free 随便", "feel good 感觉良好"],
  "few": ["a few 几个", "few of 很少的…"],
  "field": ["in the field 在田野里", "field trip 实地考察"],
  "fifteen": ["fifteen years 十五年", "age fifteen 十五岁"],
  "fifty": ["fifty percent 百分之五十", "fifty years 五十年"],
  "fight": ["fight for 为…而战", "fight against 与…斗争"],
  "fill": ["fill in 填写", "fill with 充满"],
  "film": ["see a film 看电影", "a film star 电影明星"],
  "final": ["final exam 期末考试", "in the final 在决赛中"],
  "find": ["find out 查明", "find it hard 觉得难"],
  "fine": ["fine weather 好天气", "That's fine 那很好"],
  "finger": ["lift a finger 帮一点忙", "finger food 手拿食物"],
  "finish": ["finish doing 做完", "finish line 终点线"],
  "fire": ["on fire 着火", "fire station 消防站", "set fire 放火"],
  "first": ["first of all 首先", "at first 起初", "first name 名"],
  "fish": ["go fishing 去钓鱼", "fish and chips 炸鱼薯条"],
  "five": ["five o'clock 五点钟", "five years 五年"],
  "fix": ["fix up 修理好", "fix a date 定日期"],
  "flag": ["raise the flag 升旗", "national flag 国旗"],
  "flat": ["flat tire 瘪胎", "a flat 一套公寓"],
  "floor": ["on the floor 在地板上", "first floor 一楼"],
  "flower": ["a bunch of flowers 一束花", "flower shop 花店"],
  "fly": ["fly to 飞往", "fly a kite 放风筝"],
  "fog": ["in a fog 困惑的", "heavy fog 浓雾"],
  "follow": ["follow up 跟进", "follow the rule 遵守规则"],
  "food": ["fast food 快餐", "food and drink 饮食"],
  "foot": ["on foot 步行", "at the foot of 在…脚下"],
  "forest": ["in the forest 在森林里", "forest fire 森林火灾"],
  "forget": ["forget to do 忘记做", "forget about 忘掉"],
  "fork": ["a knife and fork 一副刀叉", "fork out 支付"],
  "form": ["in the form of 以…形式", "fill in a form 填表"],
  "forty": ["forty years 四十年", "forty percent 百分之四十"],
  "four": ["four seasons 四季", "four o'clock 四点钟"],
  "free": ["for free 免费", "free time 空闲时间", "feel free 请随意"],
  "fresh": ["fresh air 新鲜空气", "fresh fruit 新鲜水果"],
  "friday": ["on Friday 在周五", "Friday night 周五晚"],
  "friend": ["make friends 交朋友", "best friend 最好的朋友"],
  "from": ["from now on 从现在起", "far from 远离", "from...to 从…到"],
  "front": ["in front of 在…前面", "front door 前门"],
  "fruit": ["a piece of fruit 一份水果", "fruit juice 果汁"],
  "full": ["full of 充满", "be full 满了", "full name 全名"],
  "fun": ["have fun 玩得开心", "for fun 为了好玩"],
  "future": ["in the future 将来", "future plan 未来计划"],
  "game": ["a ball game 球类运动", "video game 电子游戏"],
  "garden": ["in the garden 在花园里", "garden party 游园会"],
  "gate": ["at the gate 在门口", "school gate 校门"],
  "general": ["in general 总的来说", "general idea 大意"],
  "get": ["get up 起床", "get on 上车", "get along 相处"],
  "gift": ["a gift for 给…的礼物", "birthday gift 生日礼物"],
  "girl": ["a little girl 小女孩", "girl friend 女朋友"],
  "give": ["give up 放弃", "give out 分发", "give a hand 帮忙"],
  "glad": ["glad to 很高兴", "be glad 高兴的"],
  "glass": ["a glass of 一杯", "a pair of glasses 一副眼镜"],
  "go": ["go on 继续", "go ahead 去吧", "go for it 加油"],
  "goat": ["a goat 一只山羊", "goat milk 山羊奶"],
  "gold": ["gold medal 金牌", "gold fish 金鱼"],
  "good": ["be good at 擅长", "good luck 祝好运", "good night 晚安"],
  "grandfather": ["my grandfather 我爷爷", "grandfather clock 落地钟"],
  "grandmother": ["my grandmother 我奶奶", "visit grandmother 看望奶奶"],
  "grass": ["on the grass 在草地上", "green grass 绿草"],
  "great": ["great idea 好主意", "a great deal 许多"],
  "green": ["green tea 绿茶", "green hand 新手"],
  "grey": ["grey hair 灰白头发", "grey sky 灰蒙蒙的天"],
  "ground": ["on the ground 在地上", "ground floor 底层"],
  "group": ["a group of 一组", "study group 学习小组"],
  "grow": ["grow up 长大", "grow into 长成"],
  "guess": ["guess what 猜猜看", "make a guess 猜一下"],
  "guest": ["guest room 客房", "honored guest 贵宾"],
  "guide": ["tour guide 导游", "user guide 使用指南"],
  "guitar": ["play the guitar 弹吉他", "guitar player 吉他手"],
  "half": ["half an hour 半小时", "in half 成两半"],
  "hand": ["hand in 上交", "hand out 分发", "on hand 在手边"],
  "happen": ["happen to 碰巧", "what happened 发生了什么"],
  "happy": ["happy birthday 生日快乐", "happy ending 圆满结局"],
  "hard": ["work hard 努力工作", "hard time 艰难时期"],
  "hat": ["a hat 一顶帽子", "hat shop 帽店"],
  "hate": ["hate to do 讨厌做", "hate it 讨厌它"],
  "have": ["have to 不得不", "have a good time 玩得开心", "have lunch 吃午饭"],
  "he": ["He is a boy 他是个男孩", "He likes it 他喜欢它"],
  "head": ["head for 前往", "head teacher 班主任"],
  "healthy": ["keep healthy 保持健康", "healthy food 健康食品"],
  "hear": ["hear from 收到…的信", "hear of 听说"],
  "heart": ["heart and soul 全心全意", "break one's heart 使…心碎"],
  "heavy": ["heavy rain 大雨", "heavy traffic 拥堵交通"],
  "hello": ["say hello 打招呼", "Hello everyone 大家好"],
  "help": ["help out 帮忙", "help oneself 自取", "with the help of 在…帮助下"],
  "hen": ["a hen 一只母鸡", "hen house 鸡舍"],
  "her": ["her book 她的书", "with her 和她一起"],
  "here": ["here and there 到处", "Here you are 给你"],
  "hide": ["hide and seek 捉迷藏", "hide away 藏起来"],
  "high": ["high school 高中", "high speed 高速"],
  "hill": ["on the hill 在山上", "over the hill 走下坡路"],
  "him": ["help him 帮他", "with him 和他一起"],
  "his": ["his car 他的车", "his father 他父亲"],
  "history": ["in history 历史上", "history book 历史书"],
  "hit": ["hit on 忽然想起", "hit the target 击中目标"],
  "hold": ["hold on 等一下", "hold a meeting 开会"],
  "hole": ["a hole 一个洞", "dig a hole 挖洞"],
  "home": ["go home 回家", "at home 在家", "hometown 家乡"],
  "hope": ["hope for 希望", "hope to do 希望做"],
  "horse": ["ride a horse 骑马", "horse race 赛马"],
  "hospital": ["in hospital 住院", "go to hospital 去医院"],
  "hot": ["hot dog 热狗", "hot weather 炎热天气"],
  "hotel": ["a hotel 一家酒店", "hotel room 酒店房间"],
  "hour": ["an hour 一小时", "hour after hour 一小时又一小时"],
  "house": ["a house 一栋房子", "house work 家务"],
  "how": ["how about 怎么样", "how many 多少", "how much 多少钱"],
  "hundred": ["a hundred 一百", "hundreds of 数百"],
  "hungry": ["feel hungry 觉得饿", "go hungry 挨饿"],
  "hurry": ["hurry up 快点", "in a hurry 匆忙"],
  "ice": ["ice cream 冰淇淋", "break the ice 打破僵局"],
  "idea": ["good idea 好主意", "have no idea 不知道"],
  "if": ["if only 要是…就好了", "as if 好像"],
  "ill": ["fall ill 生病", "ill health 身体不好"],
  "important": ["important to 对…重要", "important event 重要事件"],
  "in": ["in time 及时", "in fact 事实上", "in front of 在…前面"],
  "include": ["including me 包括我", "include in 包含在"],
  "increase": ["increase by 增加了", "on the increase 在增长"],
  "inside": ["inside out 里朝外", "go inside 进去"],
  "into": ["into pieces 成碎片", "look into 调查"],
  "invite": ["invite to 邀请…到", "invite over 请来"],
  "island": ["on the island 在岛上", "a small island 小岛"],
  "it": ["It is cold 天气冷", "It doesn't matter 没关系"],
  "its": ["its color 它的颜色", "its name 它的名字"],
  "jacket": ["a jacket 一件夹克", "jacket potato 带皮烤土豆"],
  "january": ["in January 在一月", "January first 一月一日"],
  "job": ["a good job 一份好工作", "job hunting 找工作"],
  "join": ["join in 参加", "join the army 参军"],
  "juice": ["a glass of juice 一杯果汁", "orange juice 橙汁"],
  "july": ["in July 在七月", "July holiday 七月假期"],
  "jump": ["jump up 跳起来", "jump over 跳过"],
  "june": ["in June 在六月", "June holiday 六月假期"],
  "just": ["just now 刚才", "just like 就像", "just then 正在那时"],
  "keep": ["keep on 继续", "keep fit 保持健康", "keep a secret 保守秘密"],
  "key": ["key to 对…的关键", "a key 一把钥匙"],
  "kill": ["kill time 消磨时间", "kill the mood 扫兴"],
  "kind": ["kind of 有点", "a kind of 一种", "be kind to 对…友善"],
  "king": ["the king 国王", "king of 的国王"],
  "kiss": ["give a kiss 给个吻", "kiss goodbye 吻别"],
  "kitchen": ["in the kitchen 在厨房", "kitchen table 厨房桌"],
  "knee": ["on one's knee 跪着", "knee cap 膝盖骨"],
  "knife": ["a knife 一把刀", "knife and fork 刀叉"],
  "know": ["know about 了解", "know each other 互相认识", "be known as 被称为"],
  "lady": ["young lady 年轻女士", "ladies first 女士优先"],
  "lake": ["by the lake 在湖边", "a lake 一个湖"],
  "lamp": ["a lamp 一盏灯", "desk lamp 台灯"],
  "land": ["by land 走陆路", "land on 着陆"],
  "language": ["foreign language 外语", "body language 肢体语言"],
  "large": ["a large number of 大量的", "large size 大号"],
  "last": ["last but not least 最后但同样重要", "at last 终于", "last week 上周"],
  "late": ["be late for 迟到", "late at night 深夜"],
  "laugh": ["laugh at 嘲笑", "laugh out 大笑"],
  "law": ["break the law 违法", "law school 法学院"],
  "lazy": ["a lazy boy 懒男孩", "lazy day 慵懒的一天"],
  "learn": ["learn from 向…学习", "learn by heart 背诵"],
  "leave": ["leave for 动身去", "leave out 遗漏", "ask for leave 请假"],
  "left": ["on the left 在左边", "left hand 左手"],
  "leg": ["a leg 一条腿", "leg room 伸腿空间"],
  "lemon": ["a lemon 一个柠檬", "lemon tea 柠檬茶"],
  "lesson": ["have a lesson 上课", "teach a lesson 给个教训"],
  "let": ["let alone 更别提", "let go 放手"],
  "letter": ["a letter 一封信", "letter box 信箱"],
  "library": ["in the library 在图书馆", "library card 借书证"],
  "lie": ["tell a lie 说谎", "lie down 躺下"],
  "life": ["daily life 日常生活", "all one's life 一生"],
  "light": ["light up 点亮", "traffic light 红绿灯", "turn on the light 开灯"],
  "like": ["feel like 想要", "like doing 喜欢做", "look like 看起来像"],
  "line": ["in line 排队", "line up 排成队"],
  "lion": ["a lion 一头狮子", "lion dance 舞狮"],
  "list": ["a list of 一列", "shopping list 购物单"],
  "listen": ["listen to 听", "listen for 等着听"],
  "little": ["a little 一点", "little by little 一点点地"],
  "live": ["live in 住在", "live on 靠…生活", "live together 住在一起"],
  "lock": ["lock up 锁起来", "lock the door 锁门"],
  "long": ["as long as 只要", "long ago 很久以前", "no longer 不再"],
  "look": ["look at 看", "look for 寻找", "look forward to 期待"],
  "lose": ["lose weight 减肥", "lose one's way 迷路", "lose heart 灰心"],
  "lot": ["a lot of 许多", "lots of 很多"],
  "love": ["fall in love 坠入爱河", "love doing 喜欢做"],
"low": ["low price 低价", "low voice 低声"],
  "luck": ["good luck 祝好运", "bad luck 倒霉"],
  "lunch": ["have lunch 吃午饭", "lunch time 午餐时间"],
  "machine": ["washing machine 洗衣机", "a machine 一台机器"],
  "mad": ["go mad 发疯", "mad at 对…生气"],
  "magazine": ["a magazine 一本杂志", "fashion magazine 时尚杂志"],
  "mail": ["by mail 邮寄", "mail box 邮箱"],
  "main": ["main idea 主旨", "main course 主菜"],
  "make": ["make up 编造", "make friends 交朋友", "make a mistake 犯错"],
  "man": ["a young man 年轻人", "man and woman 男女"],
  "many": ["as many as 多达", "too many 太多"],
  "map": ["a map of 一张…地图", "map out 规划"],
  "march": ["in March 在三月", "march on 行进"],
  "mark": ["make a mark 做记号", "full marks 满分"],
  "market": ["super market 超市", "go to market 去市场"],
  "marry": ["get married 结婚", "marry into 嫁入"],
  "match": ["a match 一场比赛", "match with 与…相配"],
  "matter": ["no matter 无论", "What's the matter 怎么了"],
  "may": ["may be 也许是", "may as well 不妨"],
  "meal": ["three meals 三餐", "a big meal 大餐"],
  "meat": ["a piece of meat 一块肉", "meat ball 肉丸"],
  "meet": ["meet with 遇见", "nice to meet you 很高兴认识你"],
  "member": ["a member of 的会员", "family member 家庭成员"],
  "memory": ["in memory of 纪念", "good memory 好记性"],
  "men": ["men and women 男女", "old men 老人"],
  "message": ["leave a message 留言", "text message 短信"],
  "middle": ["in the middle 在中间", "middle school 中学"],
  "milk": ["a glass of milk 一杯牛奶", "milk tea 奶茶"],
  "million": ["millions of 数百万", "one in a million 万里挑一"],
  "mind": ["make up one's mind 下定决心", "change one's mind 改变主意"],
  "mine": ["a friend of mine 我的一个朋友", "This is mine 这是我的"],
  "minute": ["a minute 一分钟", "wait a minute 等一下"],
  "miss": ["miss the bus 错过公交", "miss you 想你", "miss the point 没懂重点"],
  "mistake": ["make a mistake 犯错", "by mistake 错误地"],
  "mix": ["mix up 混淆", "mix with 与…混合"],
  "model": ["a model 一个模型", "role model 榜样"],
  "modern": ["modern life 现代生活", "modern art 现代艺术"],
  "moment": ["at the moment 此刻", "just a moment 稍等"],
  "money": ["make money 赚钱", "save money 存钱"],
  "monkey": ["a monkey 一只猴子", "monkey business 胡闹"],
  "month": ["last month 上个月", "this month 这个月"],
  "moon": ["moon cake 月饼", "full moon 满月"],
  "more": ["more than 超过", "what's more 而且", "no more 不再"],
  "morning": ["in the morning 在早上", "good morning 早上好"],
  "most": ["most of 大多数", "at most 至多"],
  "mother": ["mother tongue 母语", "mother and child 母子"],
  "mountain": ["a mountain 一座山", "climb the mountain 爬山"],
  "mouse": ["a mouse 一只老鼠", "mouse pad 鼠标垫"],
  "mouth": ["open one's mouth 张嘴", "from mouth to mouth 口口相传"],
  "move": ["move on 继续前进", "move in 搬进", "move house 搬家"],
  "movie": ["see a movie 看电影", "movie star 电影明星"],
  "much": ["too much 太多", "as much as 尽…多", "thank you very much 非常感谢"],
  "music": ["listen to music 听音乐", "music room 音乐室"],
  "must": ["must do 必须做", "must be 一定是"],
  "my": ["my book 我的书", "my friend 我的朋友"],
  "name": ["name after 以…命名", "first name 名"],
  "nationality": ["What's your nationality 你的国籍", "Chinese nationality 中国国籍"],
  "natural": ["natural beauty 自然美", "natural gas 天然气"],
  "nature": ["in nature 本质上", "Mother Nature 大自然"],
  "near": ["near by 在附近", "near to 靠近"],
  "neck": ["neck and neck 不分上下", "a stiff neck 落枕"],
  "need": ["in need 在危难中", "need to do 需要做"],
  "never": ["never mind 没关系", "never before 以前从未"],
  "new": ["brand new 崭新的", "new friend 新朋友"],
  "news": ["a piece of news 一则新闻", "good news 好消息"],
  "newspaper": ["a newspaper 一份报纸", "read the newspaper 看报"],
  "next": ["next to 紧挨着", "next time 下次", "next week 下周"],
  "nice": ["nice to meet you 很高兴认识你", "nice day 好天气"],
  "night": ["at night 在夜晚", "good night 晚安"],
  "nine": ["nine e'clock 九点钟", "nine years 九年"],
  "nineteen": ["nineteen years 十九年", "age nineteen 十九岁"],
  "ninety": ["ninety percent 百分之九十", "ninety years 九十年"],
  "no": ["no longer 不再", "no problem 没问题", "no way 没门"],
  "north": ["in the north 在北方", "North America 北美"],
  "nose": ["blow one's nose 擤鼻涕", "under one's nose 当着面"],
  "not": ["not at all 一点也不", "not only 不仅"],
  "note": ["take notes 做笔记", "leave a note 留便条"],
 "nothing": ["nothing but 只有", "nothing else 没别的"],
  "notice": ["take notice 注意到", "give notice 通知"],
  "november": ["in November 在十一月", "November holiday 十一月假期"],
  "now": ["from now on 从现在起", "just now 刚才", "now and then 偶尔"],
  "number": ["a number of 若干", "phone number 电话号码"],
  "nurse": ["a nurse 一名护士", "head nurse 护士长"],
  "object": ["an object 一个物体", "object to 反对"],
  "ocean": ["in the ocean 在海洋里", "ocean wave 海浪"],
  "october": ["in October 在十月", "October holiday 十月假期"],
  "off": ["off and on 断断续续", "take off 脱下", "turn off 关掉"],
  "office": ["in the office 在办公室", "post office 邮局"],
  "often": ["how often 多久一次", "very often 经常"],
  "oil": ["cooking oil 食用油", "oil painting 油画"],
  "old": ["how old 多大年纪", "old friend 老朋友", "grow old 变老"],
  "on": ["on time 准时", "on foot 步行", "on duty 值班"],
  "once": ["once upon a time 从前", "at once 立刻", "once more 再一次"],
  "one": ["one by one 一个接一个", "one of 之一"],
  "only": ["only if 只有", "not only 不仅"],
  "open": ["open up 开放", "open the door 开门"],
  "or": ["or so 大约", "either...or 要么…要么"],
  "orange": ["orange juice 橙汁", "an orange 一个橙子"],
  "order": ["in order 按顺序", "order food 点餐", "out of order 故障"],
  "other": ["each other 互相", "the other 另一个", "other than 除了"],
  "our": ["our school 我们学校", "our home 我们的家"],
  "out": ["out of 出于", "out of order 坏了", "find out 查明"],
  "outside": ["outside the door 门外", "go outside 出去"],
  "over": ["over and over 反复", "over there 在那边", "all over 到处"],
  "own": ["on one's own 独自", "own a car 拥有车"],
  "page": ["a page 一页", "home page 主页"],
  "pain": ["in pain 痛苦地", "pain killer 止痛药"],
  "paint": ["paint a picture 画画", "paint the wall 刷墙"],
  "pair": ["a pair of 一双", "a pair 一对"],
  "paper": ["a piece of paper 一张纸", "paper cut 剪纸"],
  "parent": ["parent meeting 家长会", "single parent 单亲"],
  "park": ["in the park 在公园", "park the car 停车"],
  "part": ["take part in 参加", "part of 的一部分"],
  "party": ["birthday party 生日聚会", "have a party 开派对"],
  "pass": ["pass by 经过", "pass the exam 通过考试"],
  "past": ["in the past 过去", "past tense 过去时"],
  "pay": ["pay for 为…付钱", "pay attention 注意"],
  "pen": ["a pen 一支笔", "pen pal 笔友"],
  "pencil": ["a pencil 一支铅笔", "pencil case 铅笔盒"],
  "people": ["young people 年轻人", "people say 人们说"],
  "pepper": ["black pepper 黑胡椒", "red pepper 红辣椒"],
  "percent": ["fifty percent 百分之五十", "a percent 百分之一"],
  "perfect": ["perfect for 非常适合", "perfect score 满分"],
  "person": ["in person 亲自", "a nice person 好人"],
  "pet": ["a pet dog 宠物狗", "keep a pet 养宠物"],
  "phone": ["by phone 打电话", "phone number 电话号码"],
  "photo": ["take a photo 拍照", "a photo of 一张…的照片"],
  "phrase": ["a phrase 一个短语", "useful phrase 实用短语"],
  "physics": ["physics lab 物理实验室", "learn physics 学物理"],
  "piano": ["play the piano 弹钢琴", "piano lesson 钢琴课"],
  "pick": ["pick up 捡起", "pick out 挑出"],
  "picture": ["take a picture 拍照", "a picture of 一张…的画"],
  "piece": ["a piece of 一片", "a piece 一块"],
  "pig": ["a pig 一头猪", "pig farm 养猪场"],
  "pill": ["a pill 一片药", "sleeping pill 安眠药"],
  "place": ["in place 在适当位置", "take place 发生", "place of interest 名胜"],
  "plan": ["plan to do 计划做", "make a plan 制定计划"],
  "plane": ["by plane 乘飞机", "catch a plane 赶飞机"],
  "plant": ["plant a tree 种树", "a plant 一株植物"],
  "plate": ["a plate of 一盘", "on a plate 在盘子里"],
  "play": ["play with 玩", "play the piano 弹钢琴", "play sports 做运动"],
  "please": ["please do 请做", "Yes please 好的麻烦了"],
  "pocket": ["in one's pocket 在口袋里", "pocket money 零花钱"],
  "poem": ["a poem 一首诗", "write a poem 写诗"],
  "point": ["point out 指出", "point at 指向", "to the point 切题"],
  "police": ["police station 警察局", "call the police 报警"],
  "poor": ["poor man 穷人", "poor health 身体差"],
  "popular": ["be popular with 受…欢迎", "popular song 流行歌"],
  "position": ["in position 就位", "job position 职位"],
  "possible": ["as...as possible 尽可能", "if possible 如果可能"],
  "post": ["post office 邮局", "post a letter 寄信"],
  "potato": ["a potato 一个土豆", "potato chips 薯片"],
  "pour": ["pour out 倒出", "pour into 倒入"],
  "power": ["power off 关机", "power station 发电站"],
  "practice": ["practice doing 练习做", "practice makes perfect 熟能生巧"],
  "present": ["at present 目前", "a present 一份礼物", "present to 把…介绍给"],
  "pretty": ["pretty girl 漂亮女孩", "pretty good 相当好"],
  "price": ["high price 高价", "price tag 价签"],
  "prince": ["a prince 一位王子", "prince charming 白马王子"],
  "print": ["print out 打印出来", "in print 已出版"],
  "prize": ["win a prize 获奖", "first prize 一等奖"],
  "problem": ["no problem 没问题", "solve a problem 解决问题"],
  "produce": ["produce from 由…生产", "produce goods 生产商品"],
  "program": ["a TV program 电视节目", "program design 程序设计"],
  "project": ["a project 一个项目", "project work 课题"],
  "promise": ["keep a promise 信守承诺", "make a promise 许诺"],
  "protect": ["protect from 保护…免受", "protect the environment 保护环境"],
  "prove": ["prove to be 证明是", "prove oneself 证明自己"],
  "public": ["in public 公开地", "public place 公共场所"],
  "pull": ["pull down 拆毁", "pull up 停下", "pull out 拔出"],
  "pumpkin": ["a pumpkin 一个南瓜", "pumpkin pie 南瓜派"],
  "push": ["push up 推高", "push the door 推门"],
  "put": ["put on 穿上", "put off 推迟", "put away 收好"],
  "quality": ["high quality 高质量", "good quality 好品质"],
  "question": ["ask a question 提问", "out of question 没问题"],
  "quick": ["quick to 很快", "be quick 快点"],
  "quiet": ["keep quiet 保持安静", "quiet night 宁静的夜"],
  "quite": ["quite a 相当", "quite good 相当好"],
  "rabbit": ["a rabbit 一只兔子", "rabbit hole 兔子洞"],
  "rain": ["rain cats and dogs 倾盆大雨", "in the rain 在雨中"],
  "raise": ["raise money 筹款", "raise children 养育孩子"],
  "reach": ["reach for 伸手去够", "reach out 伸出"],
  "read": ["read out 朗读", "read a book 读书"],
  "ready": ["get ready 准备好", "ready to do 准备做"],
  "real": ["real life 现实生活", "for real 真的"],
  "reason": ["for some reason 出于某种原因", "the reason for …的原因"],
  "receive": ["receive a letter 收到信", "receive from 从…收到"],
  "red": ["red light 红灯", "red face 红脸"],
  "remember": ["remember to do 记得做", "remember me 记得我"],
  "repeat": ["repeat after 跟读", "repeat again 再重复"],
  "reply": ["reply to 回复", "no reply 无回复"],
  "report": ["report to 向…报告", "weather report 天气预报"],
  "rest": ["have a rest 休息一下", "the rest of 其余的"],
  "rice": ["a bowl of rice 一碗米饭", "rice field 稻田"],
  "rich": ["rich in 富含", "a rich man 富人"],
  "ride": ["ride a bike 骑自行车", "give a ride 搭便车"],
  "right": ["all right 好的", "right away 立刻", "right now 现在"],
  "ring": ["ring up 打电话", "a ring 一枚戒指"],
  "river": ["a river 一条河", "river bank 河岸"],
  "road": ["on the road 在路上", "road sign 路标"],
  "rob": ["rob of 抢劫", "rob the bank 抢银行"],
  "robot": ["a robot 一个机器人", "robot dog 机器狗"],
  "rock": ["rock music 摇滚乐", "a rock 一块石头"],
  "room": ["make room 腾出空间", "living room 客厅"],
  "round": ["all round 周围", "round the clock 昼夜不停"],
  "rubber": ["a rubber 一块橡皮", "rubber band 橡皮筋"],
  "rule": ["break the rule 违规", "as a rule 通常"],
  "run": ["run out 用完", "run away 逃跑", "run into 偶遇"],
  "sad": ["feel sad 感到难过", "sad story 伤心的故事"],
  "safe": ["safe and sound 平安无事", "keep safe 保持安全"],
  "sail": ["sail away 扬帆远去", "go sailing 去航行"],
  "salad": ["a salad 一份沙拉", "fruit salad 水果沙拉"],
  "sale": ["for sale 出售", "on sale 打折"],
  "salt": ["a salt 盐", "salt water 盐水"],
  "same": ["the same as 和…一样", "same to you 你也一样"],
  "sand": ["a grain of sand 一粒沙", "sand beach 沙滩"],
  "save": ["save money 存钱", "save the file 保存文件"],
  "say": ["say sorry 说抱歉", "that is to say 也就是说"],
  "school": ["go to school 上学", "primary school 小学"],
  "science": ["science museum 科学馆", "natural science 自然科学"],
  "sea": ["by sea 走海路", "sea food 海鲜"],
  "season": ["four seasons 四季", "in season 应季"],
  "seat": ["take a seat 坐下", "window seat 靠窗座位"],
  "second": ["second to none 首屈一指", "in a second 立刻"],
  "secret": ["keep a secret 保守秘密", "in secret 秘密地"],
  "see": ["see off 送别", "see you 再见", "see a doctor 看医生"],
  "seed": ["a seed 一颗种子", "seed oil 籽油"],
  "sell": ["sell out 售罄", "sell well 畅销"],
  "send": ["send for 派人去请", "send a message 发消息"],
  "sentence": ["a sentence 一个句子", "death sentence 死刑"],
  "september": ["in September 在九月", "September holiday 九月假期"],
  "serve": ["serve as 充当", "serve the people 为人民服务"],
  "seven": ["seven e'clock 七点钟", "seven years 七年"],
  "seventeen": ["seventeen years 十七年", "age seventeen 十七岁"],
  "seventy": ["seventy percent 百分之七十", "seventy years 七十年"],
  "several": ["several times 几次", "several of 几个…"],
  "shake": ["shake hands 握手", "shake off 摆脱"],
  "shall": ["shall we 我们…好吗", "I shall 我将"],
  "shape": ["in shape 处于良好状态", "out of shape 变形"],
  "share": ["share with 与…分享", "share the cost 分摊费用"],
  "she": ["She is a girl 她是个女孩", "She likes it 她喜欢它"],
  "sheep": ["a sheep 一只羊", "black sheep 害群之马"],
  "sheet": ["a sheet of 一张", "bed sheet 床单"],
  "shelf": ["on the shelf 在架子上", "book shelf 书架"],
  "ship": ["by ship 乘船", "a ship 一艘船"],
  "shirt": ["a shirt 一件衬衫", "T-shirt T恤"],
  "shoe": ["a pair of shoes 一双鞋", "shoe shop 鞋店"],
  "shop": ["go shopping 去购物", "shop assistant 店员"],
  "short": ["in short 简而言之", "short hair 短发", "be short of 缺乏"],
  "should": ["should do 应该做", "should not 不应该"],
  "show": ["show up 出现", "show off 炫耀", "on show 在展出"],
  "shut": ["shut up 闭嘴", "shut down 关闭"],
  "sick": ["be sick of 厌烦", "feel sick 觉得恶心"],
  "side": ["by the side of 在…旁边", "on the side 在一旁"],
  "sign": ["sign up 报名", "road sign 路标"],
  "silk": ["silk road 丝绸之路", "silk dress 丝绸裙"],
  "sing": ["sing a song 唱歌", "sing along 跟唱"],
  "single": ["single room 单人间", "a single 一个单身者"],
  "sister": ["elder sister 姐姐", "younger sister 妹妹"],
  "sit": ["sit down 坐下", "sit up 坐直"],
  "six": ["six e'clock 六点钟", "six years 六年"],
  "sixteen": ["sixteen years 十六年", "age sixteen 十六岁"],
  "sixty": ["sixty percent 百分之六十", "sixty years 六十年"],
  "size": ["what size 什么尺码", "large size 大号"],
  "skill": ["skill at 在…方面的技巧", "life skill 生活技能"],
  "skin": ["skin deep 肤浅的", "skin care 护肤"],
  "skirt": ["a skirt 一条裙子", "short skirt 短裙"],
  "sleep": ["go to sleep 入睡", "sleep well 睡得好"],
  "slow": ["slow down 慢下来", "slow music 舒缓音乐"],
  "small": ["a small town 小镇", "small talk 闲聊"],
  "smell": ["smell good 闻起来香", "bad smell 臭味"],
  "smile": ["smile at 对…微笑", "with a smile 微笑着"],
  "snow": ["a snow 一场雪", "snow man 雪人"],
  "so": ["so that 以便", "so far 到目前为止", "so good 还不错"],
  "soap": ["a bar of soap 一块肥皂", "soap opera 肥皂剧"],
  "soccer": ["play soccer 踢足球", "soccer ball 足球"],
  "social": ["social media 社交媒体", "social life 社交生活"],
  "sock": ["a pair of socks 一双袜子", "sock puppet 袜子玩偶"],
  "soft": ["soft drink 软饮", "soft voice 轻柔的声音"],
  "some": ["some of 一些", "some day 有朝一日"],
  "son": ["my son 我儿子", "son and daughter 儿女"],
  "song": ["a folk song 民歌", "sing a song 唱歌"],
  "soon": ["as soon as 一…就", "see you soon 回头见"],
  "sorry": ["say sorry 说抱歉", "I'm sorry 对不起"],
  "sound": ["sound like 听起来像", "make a sound 发出声音"],
  "soup": ["a bowl of soup 一碗汤", "chicken soup 鸡汤"],
  "south": ["in the south 在南方", "South America 南美"],
  "space": ["in space 在太空", "space ship 宇宙飞船"],
  "speak": ["speak up 大声说", "speak English 说英语"],
  "special": ["special offer 特价", "something special 特别的东西"],
  "speed": ["speed up 加速", "at full speed 全速"],
  "spell": ["spell out 拼写出来", "spell the word 拼单词"],
  "spend": ["spend on 在…上花费", "spend time 花时间"],
  "spring": ["in spring 在春天", "spring water 泉水"],
  "square": ["a square 一个广场", "square meter 平方米"],
  "stamp": ["a stamp 一张邮票", "stamp collecting 集邮"],
  "stand": ["stand up 站起来", "stand for 代表"],
  "star": ["a movie star 电影明星", "star light 星光"],
  "start": ["start with 以…开始", "start to do 开始做"],
  "station": ["train station 火车站", "bus station 汽车站"],
  "stay": ["stay up 熬夜", "stay at home 待在家"],
  "step": ["step by step 一步步地", "watch one's step 走路小心"],
  "still": ["still life 静物", "stand still 站着别动"],
  "stop": ["stop by 顺道拜访", "stop doing 停止做"],
  "store": ["a store 一家商店", "book store 书店"],
  "storm": ["a storm 一场暴风雨", "brain storm 头脑风暴"],
  "story": ["tell a story 讲故事", "a short story 短篇小说"],
  "street": ["on the street 在街上", "street light 路灯"],
  "strong": ["strong point 长处", "strong coffee 浓咖啡"],
  "student": ["a student 一名学生", "student card 学生证"],
  "study": ["study hard 努力学习", "study abroad 留学"],
  "stupid": ["a stupid idea 蠢主意", "stupid mistake 愚蠢的错误"],
  "subject": ["a subject 一门学科", "subject to 受…支配"],
  "success": ["a big success 巨大成功", "wish you success 祝你成功"],
  "such": ["such as 例如", "such a 如此的…"],
  "summer": ["in summer 在夏天", "summer holiday 暑假"],
  "sun": ["sun rise 日出", "under the sun 天下"],
  "sunny": ["a sunny day 晴天", "sunny side 向阳面"],
  "supper": ["have supper 吃晚饭", "supper time 晚餐时间"],
  "support": ["support oneself 养活自己", "in support of 支持"],
  "sure": ["be sure to 一定要", "for sure 确定", "make sure 确保"],
  "surface": ["on the surface 表面上", "water surface 水面"],
  "sweet": ["sweet tooth 爱吃甜食", "sweet dream 美梦"],
  "swim": ["go swimming 去游泳", "swim across 游过"],
  "table": ["at the table 在桌旁", "set the table 摆餐具"],
  "take": ["take off 脱下", "take care 当心", "take a bus 乘公交"],
  "talk": ["talk about 谈论", "talk to 对…说话"],
  "tall": ["a tall boy 高个子男孩", "tall building 高楼"],
  "taste": ["taste good 尝起来好", "good taste 好品味"],
  "taxi": ["by taxi 乘出租", "take a taxi 打的"],
  "tea": ["a cup of tea 一杯茶", "green tea 绿茶"],
  "teach": ["teach oneself 自学", "teach a lesson 给教训"],
  "team": ["a team 一支队伍", "team work 团队合作"],
  "tear": ["tear down 拆除", "in tears 含泪"],
  "telephone": ["by telephone 打电话", "telephone number 电话号码"],
  "television": ["watch television 看电视", "television show 电视节目"],
  "tell": ["tell a lie 说谎", "tell apart 区分", "tell the time 看时间"],
  "ten": ["ten e'clock 十点钟", "ten years 十年"],
  "tennis": ["play tennis 打网球", "tennis court 网球场"],
  "term": ["in terms of 就…而言", "this term 这学期"],
  "test": ["take a test 参加考试", "test paper 试卷"],
  "text": ["text message 短信", "text book 课本"],
  "than": ["rather than 而不是", "more than 多于"],
  "thank": ["thank you 谢谢你", "thank goodness 谢天谢地"],
  "that": ["that is 也就是说", "that's all 就这些"],
  "the": ["the same 同样的", "the other 另一个"],
  "their": ["their house 他们的房子", "their friends 他们的朋友"],
  "them": ["help them 帮他们", "with them 和他们一起"],
  "then": ["and then 然后", "since then 从那时起"],
  "there": ["over there 在那边", "there is 有"],
  "these": ["these days 如今", "these books 这些书"],
  "they": ["They are students 他们是学生", "they like 他们喜欢"],
  "thin": ["thin air 稀薄空气", "thin ice 薄冰"],
  "thing": ["one thing 一件事", "the whole thing 整件事"],
  "think": ["think about 考虑", "think of 想起", "think over 仔细考虑"],
  "third": ["third party 第三方", "one third 三分之一"],
  "thirsty": ["feel thirsty 觉得渴", "thirsty for 渴望"],
  "thirteen": ["thirteen years 十三年", "age thirteen 十三岁"],
  "thirty": ["thirty percent 百分之三十", "thirty years 三十年"],
  "this": ["this way 这边", "this morning 今天早上"],
  "those": ["those days 那些日子", "those people 那些人"],
  "though": ["even though 即使", "as though 好像"],
  "three": ["three e'clock 三点钟", "three times 三次"],
  "throat": ["have a sore throat 嗓子疼", "clear one's throat 清嗓子"],
  "through": ["through and through 彻头彻尾", "go through 经历"],
  "throw": ["throw away 扔掉", "throw up 呕吐"],
  "thursday": ["on Thursday 在周四", "Thursday night 周四晚"],
  "ticket": ["a ticket 一张票", "ticket office 售票处"],
  "time": ["on time 准时", "all the time 一直", "have a good time 玩得开心"],
  "tiny": ["a tiny dog 小狗", "tiny bit 一点点"],
  "tired": ["feel tired 觉得累", "tired of 厌烦"],
  "to": ["to and fro 来回", "to some extent 在某种程度上"],
  "today": ["today's news 今日新闻", "today is fine 今天天气好"],
  "together": ["get together 聚在一起", "together with 与…一起"],
  "toilet": ["go to the toilet 上厕所", "toilet paper 厕纸"],
  "tomato": ["a tomato 一个番茄", "tomato soup 番茄汤"],
  "tomorrow": ["see you tomorrow 明天见", "tomorrow morning 明天早上"],
  "tonight": ["tonight's news 今晚新闻", "see you tonight 今晚见"],
  "too": ["too much 太多", "too...to 太…而不能", "me too 我也是"],
  "tooth": ["brush one's teeth 刷牙", "tooth ache 牙痛"],
  "top": ["on top of 在…之上", "top student 优等生"],
  "total": ["in total 总共", "a total of 总计"],
  "touch": ["touch on 提及", "keep in touch 保持联系"],
  "tour": ["go on a tour 去旅游", "tour guide 导游"],
  "town": ["a small town 小镇", "go to town 进城"],
  "toy": ["a toy 一个玩具", "toy car 玩具车"],
  "trade": ["trade in 做…生意", "world trade 世界贸易"],
  "traffic": ["traffic jam 交通堵塞", "traffic light 红绿灯"],
  "train": ["by train 乘火车", "catch a train 赶火车"],
  "travel": ["travel abroad 出国旅游", "travel agent 旅行社"],
  "tree": ["a tree 一棵树", "family tree 家谱"],
  "trip": ["a trip to 去…的旅行", "business trip 出差"],
  "trouble": ["in trouble 有麻烦", "get into trouble 惹麻烦"],
  "truck": ["a truck 一辆卡车", "truck driver 卡车司机"],
  "true": ["come true 实现", "true friend 真朋友"],
  "try": ["try on 试穿", "try one's best 尽力", "try out 试验"],
  "tuesday": ["on Tuesday 在周二", "Tuesday night 周二晚"],
  "turn": ["turn on 打开", "turn off 关掉", "turn around 转身"],
  "twelve": ["twelve e'clock 十二点", "twelve years 十二年"],
  "twenty": ["twenty years 二十年", "twenty percent 百分之二十"],
  "two": ["two e'clock 两点", "two sides 两边"],
  "ugly": ["an ugly duckling 丑小鸭", "ugly face 丑陋的脸"],
  "uncle": ["my uncle 我叔叔", "uncle and aunt 叔婶"],
  "under": ["under control 在控制下", "under the tree 在树下"],
  "understand": ["make oneself understood 使别人理解自己", "understand each other 互相理解"],
  "unit": ["a unit 一个单元", "unit price 单价"],
  "until": ["not until 直到…才", "wait until 等到"],
  "up": ["up and down 上上下下", "up to 多达", "get up 起床"],
  "use": ["use up 用完", "make use of 利用"],
  "useful": ["useful skill 实用技能", "be useful 有用"],
  "usual": ["as usual 像往常一样", "unusual 不寻常的"],
  "vacation": ["on vacation 在度假", "summer vacation 暑假"],
  "valley": ["a valley 一个山谷", "in the valley 在山谷里"],
  "value": ["good value 物有所值", "value of …的价值"],
  "vegetable": ["a vegetable 一种蔬菜", "green vegetable 青菜"],
  "very": ["very much 非常", "very good 很好"],
  "victory": ["a victory 一场胜利", "win a victory 获胜"],
  "video": ["a video 一段视频", "video game 电子游戏"],
  "village": ["a village 一个村庄", "village school 乡村学校"],
  "visit": ["visit a friend 拜访朋友", "pay a visit 访问"],
  "voice": ["in a low voice 低声地", "voice mail 语音信箱"],
  "wait": ["wait for 等待", "wait a minute 等一下"],
  "wake": ["wake up 醒来", "stay awake 保持清醒"],
  "walk": ["go for a walk 去散步", "walk to school 走路去上学"],
  "wall": ["a wall 一面墙", "wall painting 壁画"],
  "want": ["want to do 想要做", "want for 缺少"],
  "warm": ["keep warm 保暖", "warm heart 热心"],
  "wash": ["wash up 洗漱", "wash clothes 洗衣服"],
  "watch": ["watch out 当心", "watch TV 看电视"],
  "water": ["a glass of water 一杯水", "water fall 瀑布"],
  "wave": ["wave to 向…挥手", "heat wave 热浪"],
  "way": ["by the way 顺便说", "in a way 在某种程度上", "on the way 在路上"],
  "we": ["We are friends 我们是朋友", "we can 我们能"],
  "wear": ["wear out 穿破", "wear a coat 穿外套"],
  "weather": ["fine weather 好天气", "weather report 天气预报"],
  "wednesday": ["on Wednesday 在周三", "Wednesday night 周三晚"],
  "week": ["this week 本周", "week after week 一周又一周"],
  "weight": ["lose weight 减肥", "put on weight 增重"],
  "welcome": ["You're welcome 不客气", "welcome to 欢迎来到"],
  "well": ["as well 也", "get well 康复", "do well 做得好"],
  "west": ["in the west 在西方", "West Asia 西亚"],
  "wet": ["get wet 弄湿", "wet weather 潮湿天气"],
  "what": ["what about 怎么样", "What's up 怎么了"],
  "wheel": ["a wheel 一个轮子", "wheel chair 轮椅"],
  "when": ["when it comes to 当谈到", "since when 从何时起"],
  "where": ["where to 去哪儿", "where else 别的地方"],
  "which": ["which one 哪一个", "of which 其中"],
  "white": ["white hair 白发", "white wine 白葡萄酒"],
 "who": ["who knows 谁知道", "who else 还有谁"],
  "whole": ["as a whole 总体上", "the whole day 一整天"],
  "whose": ["whose book 谁的书", "whose turn 轮到谁"],
  "why": ["why not 为什么不", "why bother 何必"],
  "wide": ["wide open 大敞着", "wide world 广阔世界"],
  "wife": ["my wife 我妻子", "wife and children 妻儿"],
  "will": ["will do 将会做", "at will 随意"],
  "win": ["win a prize 获奖", "win over 说服"],
  "wind": ["wind down 放松", "wind up 上发条"],
  "window": ["a window 一扇窗", "window seat 靠窗座位"],
  "wine": ["a glass of wine 一杯酒", "red wine 红酒"],
  "winter": ["in winter 在冬天", "winter holiday 寒假"],
  "wish": ["wish for 希望得到", "best wishes 美好的祝愿"],
  "with": ["with pleasure 乐意地", "with the help of 在…帮助下", "together with 与…一起"],
  "without": ["without doubt 毫无疑问", "do without 没有…也行"],
  "woman": ["a woman 一名妇女", "woman doctor 女医生"],
  "wonder": ["wonder at 对…感到惊奇", "no wonder 难怪"],
  "wood": ["a piece of wood 一块木头", "wood house 木屋"],
  "word": ["in a word 总之", "word by word 逐字地"],
  "work": ["work out 解决", "at work 在上班", "work hard 努力工作"],
  "world": ["all over the world 全世界", "world wide 世界范围的"],
  "worry": ["worry about 担心", "no worry 别担心"],
  "worse": ["get worse 变差", "worse and worse 越来越糟"],
  "worst": ["the worst 最差的", "at worst 最坏的情况"],
  "write": ["write down 写下", "write to 给…写信"],
  "wrong": ["go wrong 出错", "what's wrong 怎么了"],
  "yard": ["a yard 一个院子", "back yard 后院"],
  "year": ["this year 今年", "year after year 年复一年"],
  "yellow": ["yellow light 黄灯", "yellow page 黄页"],
  "yes": ["say yes 同意", "yes or no 是或否"],
  "yesterday": ["yesterday's news 昨日新闻", "the day before yesterday 前天"],
  "yet": ["not yet 还没", "as yet 迄今为止"],
  "you": ["How are you 你好吗", "Thank you 谢谢你"],
  "young": ["young man 年轻人", "young and old 老少"],
  "your": ["your book 你的书", "your turn 轮到你"],
  "zero": ["zero hour 关键时刻", "below zero 零度以下"],
  "zoo": ["go to the zoo 去动物园", "zoo keeper 动物园管理员"],
  "but": ["He is young but 但他很年轻", "nothing but 只有"],
  hair: ["long HAIR 长头发","HAIR cut 理发"]
};
